name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Lint
        run: |
          make lint
      - name: Run services
        run: docker-compose up -d
      - name: Test
        env:
          HYDRA_ADMIN_URL: http://localhost:4445
        run: |
          make testacc
